[package]
name = "second-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
rocket = "0.5.0-rc.2"
lazy_static = "1.4.0"
tera = "1.17.1"
